-- ============================================================
-- HOUSING_CONDITION: 27 rows
-- ============================================================
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (1, 1, 2022, 28, 'Dwelling units - Total', 35990951);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (2, 1, 2022, 28, 'Dwelling units - Rural', 27811667);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (3, 1, 2022, 28, 'Dwelling units - Urban', 8179284);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (4, 2, 2022, 28, 'Dwelling units - Total', 2034638);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (5, 2, 2022, 28, 'Dwelling units - Rural', 1585451);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (6, 2, 2022, 28, 'Dwelling units - Urban', 449187);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (7, 3, 2022, 28, 'Dwelling units - Total', 6450133);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (8, 3, 2022, 28, 'Dwelling units - Rural', 4798755);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (9, 3, 2022, 28, 'Dwelling units - Urban', 1651378);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (10, 4, 2022, 28, 'Dwelling units - Total', 8119205);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (11, 4, 2022, 28, 'Dwelling units - Rural', 5799998);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (12, 4, 2022, 28, 'Dwelling units - Urban', 2319207);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (13, 5, 2022, 28, 'Dwelling units - Total', 4303563);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (14, 5, 2022, 28, 'Dwelling units - Rural', 3407059);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (15, 5, 2022, 28, 'Dwelling units - Urban', 896504);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (16, 6, 2022, 28, 'Dwelling units - Total', 3062378);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (17, 6, 2022, 28, 'Dwelling units - Rural', 2473786);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (18, 6, 2022, 28, 'Dwelling units - Urban', 588592);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (19, 7, 2022, 28, 'Dwelling units - Total', 5128861);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (20, 7, 2022, 28, 'Dwelling units - Rural', 4107964);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (21, 7, 2022, 28, 'Dwelling units - Urban', 1020897);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (22, 8, 2022, 28, 'Dwelling units - Total', 5007156);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (23, 8, 2022, 28, 'Dwelling units - Rural', 4049887);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (24, 8, 2022, 28, 'Dwelling units - Urban', 957269);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (25, 9, 2022, 28, 'Dwelling units - Total', 1885017);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (26, 9, 2022, 28, 'Dwelling units - Rural', 1588767);
INSERT INTO "HOUSING_CONDITION" ("HOUSING_ID", "AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE", "VALUE") VALUES (27, 9, 2022, 28, 'Dwelling units - Urban', 296250);
COMMIT;
