CREATE TABLE "AREA_LEVEL" (
    "AREA_LEVEL_ID" NUMBER(10) NOT NULL,
    "AREA_LEVEL_NAME" VARCHAR2(100),
    CONSTRAINT "PK_ALV" PRIMARY KEY ("AREA_LEVEL_ID"),
    CONSTRAINT "UK_ALV" UNIQUE ("AREA_LEVEL_NAME")
);
