CREATE TABLE "ADMINISTRATIVE_AREA" (
    "AREA_ID" NUMBER(10) NOT NULL,
    "AREA_CODE" VARCHAR2(30),
    "AREA_NAME" VARCHAR2(180),
    "AREA_LEVEL_ID" NUMBER(10),
    "PARENT_AREA_ID" NUMBER(10),
    CONSTRAINT "PK_ADM" PRIMARY KEY ("AREA_ID"),
    CONSTRAINT "FK_ADM_1" FOREIGN KEY ("AREA_LEVEL_ID") REFERENCES "AREA_LEVEL" ("AREA_LEVEL_ID"),
    CONSTRAINT "FK_ADM_2" FOREIGN KEY ("PARENT_AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID")
);
