CREATE TABLE "INDICATOR_DEFINITION" (
    "INDICATOR_ID" NUMBER(10) NOT NULL,
    "DOMAIN_NAME" VARCHAR2(60),
    "INDICATOR_NAME" VARCHAR2(250),
    "UNIT_ID" NUMBER(10),
    CONSTRAINT "PK_IND" PRIMARY KEY ("INDICATOR_ID"),
    CONSTRAINT "UK_IND" UNIQUE ("DOMAIN_NAME", "INDICATOR_NAME"),
    CONSTRAINT "FK_IND_1" FOREIGN KEY ("UNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("UNIT_ID")
);
