CREATE TABLE "POPULATION_CATEGORY" (
    "POPULATION_CATEGORY_ID" NUMBER(10) NOT NULL,
    "CATEGORY_NAME" VARCHAR2(180),
    CONSTRAINT "PK_PCAT" PRIMARY KEY ("POPULATION_CATEGORY_ID"),
    CONSTRAINT "UK_PCAT" UNIQUE ("CATEGORY_NAME")
);
