CREATE TABLE "POPULATION_DEMOGRAPHY" (
    "POPULATION_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "POPULATION_CATEGORY_ID" NUMBER(10),
    "POPULATION_COUNT" NUMBER(20),
    CONSTRAINT "PK_POP" PRIMARY KEY ("POPULATION_ID"),
    CONSTRAINT "UK_POP" UNIQUE ("AREA_ID", "YEAR", "POPULATION_CATEGORY_ID"),
    CONSTRAINT "FK_POP_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_POP_2" FOREIGN KEY ("POPULATION_CATEGORY_ID") REFERENCES "POPULATION_CATEGORY" ("POPULATION_CATEGORY_ID")
);
