CREATE TABLE "DEMOGRAPHIC_RATIO" (
    "DEMOGRAPHIC_RATIO_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "INDICATOR_ID" NUMBER(10),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_DR" PRIMARY KEY ("DEMOGRAPHIC_RATIO_ID"),
    CONSTRAINT "UK_DR" UNIQUE ("AREA_ID", "YEAR", "INDICATOR_ID"),
    CONSTRAINT "FK_DR_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_DR_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
