CREATE TABLE "HOUSEHOLD_STRUCTURE" (
    "HOUSEHOLD_STRUCTURE_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "HOUSEHOLD_TYPE" VARCHAR2(250),
    "INDICATOR_ID" NUMBER(10),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_HHS" PRIMARY KEY ("HOUSEHOLD_STRUCTURE_ID"),
    CONSTRAINT "UK_HHS" UNIQUE ("AREA_ID", "YEAR", "HOUSEHOLD_TYPE", "INDICATOR_ID"),
    CONSTRAINT "FK_HHS_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_HHS_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
