CREATE TABLE "MARITAL_STATUS" (
    "MARITAL_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "MARITAL_STATUS" VARCHAR2(250),
    "INDICATOR_ID" NUMBER(10),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_MAR" PRIMARY KEY ("MARITAL_ID"),
    CONSTRAINT "UK_MAR" UNIQUE ("AREA_ID", "YEAR", "MARITAL_STATUS", "INDICATOR_ID"),
    CONSTRAINT "FK_MAR_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_MAR_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
