CREATE TABLE "DISABILITY_PROFILE" (
    "DISABILITY_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "INDICATOR_ID" NUMBER(10),
    "DISABILITY_TYPE" VARCHAR2(250),
    "SEX" VARCHAR2(30),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_DIS" PRIMARY KEY ("DISABILITY_ID"),
    CONSTRAINT "UK_DIS" UNIQUE ("AREA_ID", "YEAR", "INDICATOR_ID", "DISABILITY_TYPE", "SEX"),
    CONSTRAINT "FK_DIS_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_DIS_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
