CREATE TABLE "EDUCATION_PROFILE" (
    "EDUCATION_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "INDICATOR_ID" NUMBER(10),
    "SEX" VARCHAR2(30),
    "RESIDENCE" VARCHAR2(100),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_EDU" PRIMARY KEY ("EDUCATION_ID"),
    CONSTRAINT "UK_EDU" UNIQUE ("AREA_ID", "YEAR", "INDICATOR_ID", "SEX", "RESIDENCE"),
    CONSTRAINT "FK_EDU_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_EDU_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
