CREATE TABLE "MIGRATION_PROFILE" (
    "MIGRATION_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "INDICATOR_ID" NUMBER(10),
    "ORIGIN_AREA_ID" NUMBER(10),
    "DESTINATION_AREA_ID" NUMBER(10),
    "MIGRATION_REASON" VARCHAR2(250),
    "SEX" VARCHAR2(30),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_MIG" PRIMARY KEY ("MIGRATION_ID"),
    CONSTRAINT "UK_MIG" UNIQUE ("AREA_ID", "YEAR", "INDICATOR_ID", "ORIGIN_AREA_ID", "DESTINATION_AREA_ID", "MIGRATION_REASON", "SEX"),
    CONSTRAINT "FK_MIG_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_MIG_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID"),
    CONSTRAINT "FK_MIG_3" FOREIGN KEY ("ORIGIN_AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_MIG_4" FOREIGN KEY ("DESTINATION_AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID")
);
