CREATE TABLE "ETHNICITY_PROFILE" (
    "ETHNICITY_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "ETHNIC_GROUP" VARCHAR2(250),
    "SEX" VARCHAR2(30),
    "INDICATOR_ID" NUMBER(10),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_ETH" PRIMARY KEY ("ETHNICITY_ID"),
    CONSTRAINT "UK_ETH" UNIQUE ("AREA_ID", "YEAR", "ETHNIC_GROUP", "SEX", "INDICATOR_ID"),
    CONSTRAINT "FK_ETH_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_ETH_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
