CREATE TABLE "DIGITAL_ACCESS" (
    "DIGITAL_ACCESS_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "INDICATOR_ID" NUMBER(10),
    "SEX" VARCHAR2(30),
    "ACCESS_CATEGORY" VARCHAR2(250),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_DIG" PRIMARY KEY ("DIGITAL_ACCESS_ID"),
    CONSTRAINT "UK_DIG" UNIQUE ("AREA_ID", "YEAR", "INDICATOR_ID", "SEX", "ACCESS_CATEGORY"),
    CONSTRAINT "FK_DIG_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_DIG_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
