CREATE TABLE "HOUSING_CONDITION" (
    "HOUSING_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "INDICATOR_ID" NUMBER(10),
    "DWELLING_TYPE" VARCHAR2(250),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_HOU" PRIMARY KEY ("HOUSING_ID"),
    CONSTRAINT "UK_HOU" UNIQUE ("AREA_ID", "YEAR", "INDICATOR_ID", "DWELLING_TYPE"),
    CONSTRAINT "FK_HOU_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_HOU_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
