CREATE TABLE "BASIC_SERVICES_ACCESS" (
    "SERVICE_ACCESS_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "YEAR" NUMBER(4),
    "INDICATOR_ID" NUMBER(10),
    "SERVICE_CATEGORY" VARCHAR2(250),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_BSA" PRIMARY KEY ("SERVICE_ACCESS_ID"),
    CONSTRAINT "UK_BSA" UNIQUE ("AREA_ID", "YEAR", "INDICATOR_ID", "SERVICE_CATEGORY"),
    CONSTRAINT "FK_BSA_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_BSA_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
