CREATE TABLE "HOUSEHOLD_EXPENDITURE" (
    "EXPENDITURE_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "SURVEY_YEAR" NUMBER(4),
    "LOCALITY" VARCHAR2(100),
    "INDICATOR_ID" NUMBER(10),
    "EXPENDITURE_CATEGORY" VARCHAR2(250),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_HEX" PRIMARY KEY ("EXPENDITURE_ID"),
    CONSTRAINT "UK_HEX" UNIQUE ("AREA_ID", "SURVEY_YEAR", "LOCALITY", "INDICATOR_ID", "EXPENDITURE_CATEGORY"),
    CONSTRAINT "FK_HEX_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_HEX_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
