CREATE TABLE "CONSUMPTION_PATTERN" (
    "CONSUMPTION_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "SURVEY_YEAR" NUMBER(4),
    "LOCALITY" VARCHAR2(100),
    "INDICATOR_ID" NUMBER(10),
    "CONSUMPTION_ITEM" VARCHAR2(250),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_CON" PRIMARY KEY ("CONSUMPTION_ID"),
    CONSTRAINT "UK_CON" UNIQUE ("AREA_ID", "SURVEY_YEAR", "LOCALITY", "INDICATOR_ID", "CONSUMPTION_ITEM"),
    CONSTRAINT "FK_CON_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_CON_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
