CREATE TABLE "POVERTY_PROFILE" (
    "POVERTY_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "SURVEY_YEAR" NUMBER(4),
    "LOCALITY" VARCHAR2(100),
    "INDICATOR_ID" NUMBER(10),
    "POVERTY_LINE_TYPE" VARCHAR2(250),
    "HOUSEHOLD_SIZE_GROUP" VARCHAR2(250),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_POV" PRIMARY KEY ("POVERTY_ID"),
    CONSTRAINT "UK_POV" UNIQUE ("AREA_ID", "SURVEY_YEAR", "LOCALITY", "INDICATOR_ID", "POVERTY_LINE_TYPE", "HOUSEHOLD_SIZE_GROUP"),
    CONSTRAINT "FK_POV_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_POV_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
