CREATE TABLE "INEQUALITY_PROFILE" (
    "INEQUALITY_ID" NUMBER(10) NOT NULL,
    "AREA_ID" NUMBER(10),
    "SURVEY_YEAR" NUMBER(4),
    "LOCALITY" VARCHAR2(100),
    "INDICATOR_ID" NUMBER(10),
    "POPULATION_GROUP" VARCHAR2(250),
    "VALUE" NUMBER(20,6),
    CONSTRAINT "PK_INEQ" PRIMARY KEY ("INEQUALITY_ID"),
    CONSTRAINT "UK_INEQ" UNIQUE ("AREA_ID", "SURVEY_YEAR", "LOCALITY", "INDICATOR_ID", "POPULATION_GROUP"),
    CONSTRAINT "FK_INEQ_1" FOREIGN KEY ("AREA_ID") REFERENCES "ADMINISTRATIVE_AREA" ("AREA_ID"),
    CONSTRAINT "FK_INEQ_2" FOREIGN KEY ("INDICATOR_ID") REFERENCES "INDICATOR_DEFINITION" ("INDICATOR_ID")
);
