CREATE TABLE `AREA_LEVEL` (
    `AREA_LEVEL_ID` INT NOT NULL,
    `AREA_LEVEL_NAME` VARCHAR(100),
    CONSTRAINT `PK_ALV` PRIMARY KEY (`AREA_LEVEL_ID`),
    CONSTRAINT `UK_ALV` UNIQUE (`AREA_LEVEL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
