CREATE TABLE `POPULATION_CATEGORY` (
    `POPULATION_CATEGORY_ID` INT NOT NULL,
    `CATEGORY_NAME` VARCHAR(180),
    CONSTRAINT `PK_PCAT` PRIMARY KEY (`POPULATION_CATEGORY_ID`),
    CONSTRAINT `UK_PCAT` UNIQUE (`CATEGORY_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
