CREATE TABLE `POPULATION_DEMOGRAPHY` (
    `POPULATION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `POPULATION_CATEGORY_ID` INT,
    `POPULATION_COUNT` BIGINT,
    CONSTRAINT `PK_POP` PRIMARY KEY (`POPULATION_ID`),
    CONSTRAINT `UK_POP` UNIQUE (`AREA_ID`, `YEAR`, `POPULATION_CATEGORY_ID`),
    CONSTRAINT `FK_POP_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_POP_2` FOREIGN KEY (`POPULATION_CATEGORY_ID`) REFERENCES `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
