CREATE TABLE `MARITAL_STATUS` (
    `MARITAL_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `MARITAL_STATUS` VARCHAR(250),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_MAR` PRIMARY KEY (`MARITAL_ID`),
    CONSTRAINT `UK_MAR` UNIQUE (`AREA_ID`, `YEAR`, `MARITAL_STATUS`, `INDICATOR_ID`),
    CONSTRAINT `FK_MAR_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_MAR_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
