CREATE TABLE `RELIGION_DISTRIBUTION` (
    `RELIGION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `RELIGION` VARCHAR(180),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_REL` PRIMARY KEY (`RELIGION_ID`),
    CONSTRAINT `UK_REL` UNIQUE (`AREA_ID`, `YEAR`, `RELIGION`, `INDICATOR_ID`),
    CONSTRAINT `FK_REL_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_REL_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
