CREATE TABLE `EDUCATION_PROFILE` (
    `EDUCATION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `SEX` VARCHAR(30),
    `RESIDENCE` VARCHAR(100),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_EDU` PRIMARY KEY (`EDUCATION_ID`),
    CONSTRAINT `UK_EDU` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `SEX`, `RESIDENCE`),
    CONSTRAINT `FK_EDU_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_EDU_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
