CREATE TABLE `MIGRATION_PROFILE` (
    `MIGRATION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `ORIGIN_AREA_ID` INT,
    `DESTINATION_AREA_ID` INT,
    `MIGRATION_REASON` VARCHAR(250),
    `SEX` VARCHAR(30),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_MIG` PRIMARY KEY (`MIGRATION_ID`),
    CONSTRAINT `UK_MIG` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `ORIGIN_AREA_ID`, `DESTINATION_AREA_ID`, `MIGRATION_REASON`, `SEX`),
    CONSTRAINT `FK_MIG_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_MIG_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`),
    CONSTRAINT `FK_MIG_3` FOREIGN KEY (`ORIGIN_AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_MIG_4` FOREIGN KEY (`DESTINATION_AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
