CREATE TABLE `BASIC_SERVICES_ACCESS` (
    `SERVICE_ACCESS_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `SERVICE_CATEGORY` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_BSA` PRIMARY KEY (`SERVICE_ACCESS_ID`),
    CONSTRAINT `UK_BSA` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `SERVICE_CATEGORY`),
    CONSTRAINT `FK_BSA_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_BSA_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
