CREATE TABLE `HOUSEHOLD_EXPENDITURE` (
    `EXPENDITURE_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `EXPENDITURE_CATEGORY` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_HEX` PRIMARY KEY (`EXPENDITURE_ID`),
    CONSTRAINT `UK_HEX` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `EXPENDITURE_CATEGORY`),
    CONSTRAINT `FK_HEX_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_HEX_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
