CREATE TABLE `INEQUALITY_PROFILE` (
    `INEQUALITY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `POPULATION_GROUP` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_INEQ` PRIMARY KEY (`INEQUALITY_ID`),
    CONSTRAINT `UK_INEQ` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `POPULATION_GROUP`),
    CONSTRAINT `FK_INEQ_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_INEQ_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
