-- ============================================================
-- POPULATION_CATEGORY: 8 rows
-- ============================================================
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (1, 'Total');
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (2, 'Male');
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (3, 'Female');
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (4, 'Hijra');
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (5, 'Rural');
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (6, 'Urban');
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (7, 'Slum');
INSERT INTO `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`, `CATEGORY_NAME`) VALUES (8, 'Floating');
COMMIT;
