-- ============================================================
-- COMMODITY: 25 rows
-- ============================================================
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (1, 'Rice', 'Food Grain');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (2, 'Wheat Flour', 'Food Grain');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (3, 'Potato', 'Vegetable');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (4, 'Onion', 'Vegetable');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (5, 'Lentil', 'Pulse');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (6, 'Soybean Oil', 'Edible Oil');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (7, 'Sugar', 'Grocery');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (8, 'Tea', 'Beverage');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (9, 'Frozen Shrimp', 'Seafood');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (10, 'Jute Fiber', 'Agricultural Raw Material');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (11, 'Leather', 'Industrial Raw Material');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (12, 'Cotton Yarn', 'Textile Raw Material');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (13, 'Knitwear', 'Garments');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (14, 'Woven Garments', 'Garments');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (15, 'Home Textile', 'Textile');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (16, 'Footwear', 'Leather Goods');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (17, 'Ceramic Products', 'Manufactured Goods');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (18, 'Pharmaceutical Products', 'Healthcare');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (19, 'Plastic Products', 'Manufactured Goods');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (20, 'Bicycle', 'Engineering Goods');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (21, 'Furniture', 'Manufactured Goods');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (22, 'Fish', 'Seafood');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (23, 'Vegetables', 'Agriculture');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (24, 'Spices', 'Food');
INSERT INTO "COMMODITY" ("COMMODITY_ID", "COMMODITY_NAME", "CATEGORY") VALUES (25, 'Processed Food', 'Food');
COMMIT;
