-- ============================================================
-- COUNTRY: 30 rows
-- ============================================================
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('BD', 'Bangladesh', 'South Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('IN', 'India', 'South Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('PK', 'Pakistan', 'South Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('LK', 'Sri Lanka', 'South Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('NP', 'Nepal', 'South Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('CN', 'China', 'East Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('JP', 'Japan', 'East Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('KR', 'South Korea', 'East Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('SG', 'Singapore', 'Southeast Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('MY', 'Malaysia', 'Southeast Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('TH', 'Thailand', 'Southeast Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('VN', 'Vietnam', 'Southeast Asia');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('AE', 'United Arab Emirates', 'Middle East');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('SA', 'Saudi Arabia', 'Middle East');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('QA', 'Qatar', 'Middle East');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('US', 'United States', 'North America');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('CA', 'Canada', 'North America');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('GB', 'United Kingdom', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('DE', 'Germany', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('FR', 'France', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('IT', 'Italy', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('ES', 'Spain', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('NL', 'Netherlands', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('BE', 'Belgium', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('SE', 'Sweden', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('CH', 'Switzerland', 'Europe');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('AU', 'Australia', 'Oceania');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('NZ', 'New Zealand', 'Oceania');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('ZA', 'South Africa', 'Africa');
INSERT INTO "COUNTRY" ("COUNTRY_CODE", "COUNTRY_NAME", "REGION") VALUES ('BR', 'Brazil', 'South America');
COMMIT;
