-- ============================================================
-- DECLARANT: 40 rows
-- ============================================================
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (1, 'Customs Declarant 001', 'Office 1, Customs Area, Dhaka');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (2, 'Customs Declarant 002', 'Office 2, Customs Area, Chattogram');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (3, 'Customs Declarant 003', 'Office 3, Customs Area, Narayanganj');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (4, 'Customs Declarant 004', 'Office 4, Customs Area, Mongla');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (5, 'Customs Declarant 005', 'Office 5, Customs Area, Benapole');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (6, 'Customs Declarant 006', 'Office 6, Customs Area, Gazipur');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (7, 'Customs Declarant 007', 'Office 7, Customs Area, Dhaka');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (8, 'Customs Declarant 008', 'Office 8, Customs Area, Chattogram');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (9, 'Customs Declarant 009', 'Office 9, Customs Area, Narayanganj');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (10, 'Customs Declarant 010', 'Office 10, Customs Area, Mongla');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (11, 'Customs Declarant 011', 'Office 11, Customs Area, Benapole');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (12, 'Customs Declarant 012', 'Office 12, Customs Area, Gazipur');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (13, 'Customs Declarant 013', 'Office 13, Customs Area, Dhaka');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (14, 'Customs Declarant 014', 'Office 14, Customs Area, Chattogram');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (15, 'Customs Declarant 015', 'Office 15, Customs Area, Narayanganj');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (16, 'Customs Declarant 016', 'Office 16, Customs Area, Mongla');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (17, 'Customs Declarant 017', 'Office 17, Customs Area, Benapole');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (18, 'Customs Declarant 018', 'Office 18, Customs Area, Gazipur');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (19, 'Customs Declarant 019', 'Office 19, Customs Area, Dhaka');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (20, 'Customs Declarant 020', 'Office 20, Customs Area, Chattogram');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (21, 'Customs Declarant 021', 'Office 21, Customs Area, Narayanganj');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (22, 'Customs Declarant 022', 'Office 22, Customs Area, Mongla');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (23, 'Customs Declarant 023', 'Office 23, Customs Area, Benapole');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (24, 'Customs Declarant 024', 'Office 24, Customs Area, Gazipur');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (25, 'Customs Declarant 025', 'Office 25, Customs Area, Dhaka');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (26, 'Customs Declarant 026', 'Office 26, Customs Area, Chattogram');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (27, 'Customs Declarant 027', 'Office 27, Customs Area, Narayanganj');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (28, 'Customs Declarant 028', 'Office 28, Customs Area, Mongla');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (29, 'Customs Declarant 029', 'Office 29, Customs Area, Benapole');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (30, 'Customs Declarant 030', 'Office 30, Customs Area, Gazipur');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (31, 'Customs Declarant 031', 'Office 31, Customs Area, Dhaka');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (32, 'Customs Declarant 032', 'Office 32, Customs Area, Chattogram');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (33, 'Customs Declarant 033', 'Office 33, Customs Area, Narayanganj');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (34, 'Customs Declarant 034', 'Office 34, Customs Area, Mongla');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (35, 'Customs Declarant 035', 'Office 35, Customs Area, Benapole');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (36, 'Customs Declarant 036', 'Office 36, Customs Area, Gazipur');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (37, 'Customs Declarant 037', 'Office 37, Customs Area, Dhaka');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (38, 'Customs Declarant 038', 'Office 38, Customs Area, Chattogram');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (39, 'Customs Declarant 039', 'Office 39, Customs Area, Narayanganj');
INSERT INTO "DECLARANT" ("DECLARANT_ID", "DECLARANT_NAME", "DECLARANT_ADDRESS") VALUES (40, 'Customs Declarant 040', 'Office 40, Customs Area, Mongla');
COMMIT;
