-- ============================================================
-- DIVISION: 8 rows
-- ============================================================
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (1, 'DIV-01', 'Dhaka');
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (2, 'DIV-02', 'Chattogram');
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (3, 'DIV-03', 'Rajshahi');
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (4, 'DIV-04', 'Khulna');
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (5, 'DIV-05', 'Barishal');
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (6, 'DIV-06', 'Sylhet');
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (7, 'DIV-07', 'Rangpur');
INSERT INTO "DIVISION" ("DIVISION_ID", "DIVISION_GEOCODE", "DIVISION_NAME") VALUES (8, 'DIV-08', 'Mymensingh');
COMMIT;
