CREATE TABLE `ADMINISTRATIVE_AREA` (
    `AREA_ID` INT NOT NULL,
    `AREA_CODE` VARCHAR(30),
    `AREA_NAME` VARCHAR(180),
    `AREA_LEVEL_ID` INT,
    `PARENT_AREA_ID` INT,
    CONSTRAINT `PK_ADM` PRIMARY KEY (`AREA_ID`),
    CONSTRAINT `FK_ADM_1` FOREIGN KEY (`AREA_LEVEL_ID`) REFERENCES `AREA_LEVEL` (`AREA_LEVEL_ID`),
    CONSTRAINT `FK_ADM_2` FOREIGN KEY (`PARENT_AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
