CREATE TABLE `MEASUREMENT_UNIT` (
    `UNIT_ID` INT NOT NULL,
    `UNIT_NAME` VARCHAR(80),
    CONSTRAINT `PK_UNT` PRIMARY KEY (`UNIT_ID`),
    CONSTRAINT `UK_UNT` UNIQUE (`UNIT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
