CREATE TABLE `INDICATOR_DEFINITION` (
    `INDICATOR_ID` INT NOT NULL,
    `DOMAIN_NAME` VARCHAR(60),
    `INDICATOR_NAME` VARCHAR(250),
    `UNIT_ID` INT,
    CONSTRAINT `PK_IND` PRIMARY KEY (`INDICATOR_ID`),
    CONSTRAINT `UK_IND` UNIQUE (`DOMAIN_NAME`, `INDICATOR_NAME`),
    CONSTRAINT `FK_IND_1` FOREIGN KEY (`UNIT_ID`) REFERENCES `MEASUREMENT_UNIT` (`UNIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
