CREATE TABLE `DEMOGRAPHIC_RATIO` (
    `DEMOGRAPHIC_RATIO_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_DR` PRIMARY KEY (`DEMOGRAPHIC_RATIO_ID`),
    CONSTRAINT `UK_DR` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`),
    CONSTRAINT `FK_DR_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_DR_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
