CREATE TABLE `HOUSEHOLD_STRUCTURE` (
    `HOUSEHOLD_STRUCTURE_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `HOUSEHOLD_TYPE` VARCHAR(250),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_HHS` PRIMARY KEY (`HOUSEHOLD_STRUCTURE_ID`),
    CONSTRAINT `UK_HHS` UNIQUE (`AREA_ID`, `YEAR`, `HOUSEHOLD_TYPE`, `INDICATOR_ID`),
    CONSTRAINT `FK_HHS_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_HHS_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
