CREATE TABLE `DISABILITY_PROFILE` (
    `DISABILITY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `DISABILITY_TYPE` VARCHAR(250),
    `SEX` VARCHAR(30),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_DIS` PRIMARY KEY (`DISABILITY_ID`),
    CONSTRAINT `UK_DIS` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `DISABILITY_TYPE`, `SEX`),
    CONSTRAINT `FK_DIS_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_DIS_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
