CREATE TABLE `ETHNICITY_PROFILE` (
    `ETHNICITY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `ETHNIC_GROUP` VARCHAR(250),
    `SEX` VARCHAR(30),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_ETH` PRIMARY KEY (`ETHNICITY_ID`),
    CONSTRAINT `UK_ETH` UNIQUE (`AREA_ID`, `YEAR`, `ETHNIC_GROUP`, `SEX`, `INDICATOR_ID`),
    CONSTRAINT `FK_ETH_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_ETH_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
