CREATE TABLE `DIGITAL_ACCESS` (
    `DIGITAL_ACCESS_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `SEX` VARCHAR(30),
    `ACCESS_CATEGORY` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_DIG` PRIMARY KEY (`DIGITAL_ACCESS_ID`),
    CONSTRAINT `UK_DIG` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `SEX`, `ACCESS_CATEGORY`),
    CONSTRAINT `FK_DIG_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_DIG_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
