CREATE TABLE `HOUSING_CONDITION` (
    `HOUSING_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `DWELLING_TYPE` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_HOU` PRIMARY KEY (`HOUSING_ID`),
    CONSTRAINT `UK_HOU` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `DWELLING_TYPE`),
    CONSTRAINT `FK_HOU_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_HOU_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
