CREATE TABLE `CONSUMPTION_PATTERN` (
    `CONSUMPTION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `CONSUMPTION_ITEM` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_CON` PRIMARY KEY (`CONSUMPTION_ID`),
    CONSTRAINT `UK_CON` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `CONSUMPTION_ITEM`),
    CONSTRAINT `FK_CON_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_CON_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
