CREATE TABLE `POVERTY_PROFILE` (
    `POVERTY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `POVERTY_LINE_TYPE` VARCHAR(250),
    `HOUSEHOLD_SIZE_GROUP` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_POV` PRIMARY KEY (`POVERTY_ID`),
    CONSTRAINT `UK_POV` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `POVERTY_LINE_TYPE`, `HOUSEHOLD_SIZE_GROUP`),
    CONSTRAINT `FK_POV_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_POV_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
