SET NAMES utf8mb4;
-- FINAL STRICT 3NF: create all 21 tables in FK-safe order.

CREATE TABLE `AREA_LEVEL` (
    `AREA_LEVEL_ID` INT NOT NULL,
    `AREA_LEVEL_NAME` VARCHAR(100),
    CONSTRAINT `PK_ALV` PRIMARY KEY (`AREA_LEVEL_ID`),
    CONSTRAINT `UK_ALV` UNIQUE (`AREA_LEVEL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ADMINISTRATIVE_AREA` (
    `AREA_ID` INT NOT NULL,
    `AREA_CODE` VARCHAR(30),
    `AREA_NAME` VARCHAR(180),
    `AREA_LEVEL_ID` INT,
    `PARENT_AREA_ID` INT,
    CONSTRAINT `PK_ADM` PRIMARY KEY (`AREA_ID`),
    CONSTRAINT `FK_ADM_1` FOREIGN KEY (`AREA_LEVEL_ID`) REFERENCES `AREA_LEVEL` (`AREA_LEVEL_ID`),
    CONSTRAINT `FK_ADM_2` FOREIGN KEY (`PARENT_AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `MEASUREMENT_UNIT` (
    `UNIT_ID` INT NOT NULL,
    `UNIT_NAME` VARCHAR(80),
    CONSTRAINT `PK_UNT` PRIMARY KEY (`UNIT_ID`),
    CONSTRAINT `UK_UNT` UNIQUE (`UNIT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `INDICATOR_DEFINITION` (
    `INDICATOR_ID` INT NOT NULL,
    `DOMAIN_NAME` VARCHAR(60),
    `INDICATOR_NAME` VARCHAR(250),
    `UNIT_ID` INT,
    CONSTRAINT `PK_IND` PRIMARY KEY (`INDICATOR_ID`),
    CONSTRAINT `UK_IND` UNIQUE (`DOMAIN_NAME`, `INDICATOR_NAME`),
    CONSTRAINT `FK_IND_1` FOREIGN KEY (`UNIT_ID`) REFERENCES `MEASUREMENT_UNIT` (`UNIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `POPULATION_CATEGORY` (
    `POPULATION_CATEGORY_ID` INT NOT NULL,
    `CATEGORY_NAME` VARCHAR(180),
    CONSTRAINT `PK_PCAT` PRIMARY KEY (`POPULATION_CATEGORY_ID`),
    CONSTRAINT `UK_PCAT` UNIQUE (`CATEGORY_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `POPULATION_DEMOGRAPHY` (
    `POPULATION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `POPULATION_CATEGORY_ID` INT,
    `POPULATION_COUNT` BIGINT,
    CONSTRAINT `PK_POP` PRIMARY KEY (`POPULATION_ID`),
    CONSTRAINT `UK_POP` UNIQUE (`AREA_ID`, `YEAR`, `POPULATION_CATEGORY_ID`),
    CONSTRAINT `FK_POP_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_POP_2` FOREIGN KEY (`POPULATION_CATEGORY_ID`) REFERENCES `POPULATION_CATEGORY` (`POPULATION_CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DEMOGRAPHIC_RATIO` (
    `DEMOGRAPHIC_RATIO_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_DR` PRIMARY KEY (`DEMOGRAPHIC_RATIO_ID`),
    CONSTRAINT `UK_DR` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`),
    CONSTRAINT `FK_DR_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_DR_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `HOUSEHOLD_STRUCTURE` (
    `HOUSEHOLD_STRUCTURE_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `HOUSEHOLD_TYPE` VARCHAR(250),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_HHS` PRIMARY KEY (`HOUSEHOLD_STRUCTURE_ID`),
    CONSTRAINT `UK_HHS` UNIQUE (`AREA_ID`, `YEAR`, `HOUSEHOLD_TYPE`, `INDICATOR_ID`),
    CONSTRAINT `FK_HHS_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_HHS_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `MARITAL_STATUS` (
    `MARITAL_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `MARITAL_STATUS` VARCHAR(250),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_MAR` PRIMARY KEY (`MARITAL_ID`),
    CONSTRAINT `UK_MAR` UNIQUE (`AREA_ID`, `YEAR`, `MARITAL_STATUS`, `INDICATOR_ID`),
    CONSTRAINT `FK_MAR_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_MAR_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `RELIGION_DISTRIBUTION` (
    `RELIGION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `RELIGION` VARCHAR(180),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_REL` PRIMARY KEY (`RELIGION_ID`),
    CONSTRAINT `UK_REL` UNIQUE (`AREA_ID`, `YEAR`, `RELIGION`, `INDICATOR_ID`),
    CONSTRAINT `FK_REL_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_REL_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DISABILITY_PROFILE` (
    `DISABILITY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `DISABILITY_TYPE` VARCHAR(250),
    `SEX` VARCHAR(30),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_DIS` PRIMARY KEY (`DISABILITY_ID`),
    CONSTRAINT `UK_DIS` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `DISABILITY_TYPE`, `SEX`),
    CONSTRAINT `FK_DIS_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_DIS_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `EDUCATION_PROFILE` (
    `EDUCATION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `SEX` VARCHAR(30),
    `RESIDENCE` VARCHAR(100),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_EDU` PRIMARY KEY (`EDUCATION_ID`),
    CONSTRAINT `UK_EDU` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `SEX`, `RESIDENCE`),
    CONSTRAINT `FK_EDU_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_EDU_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `MIGRATION_PROFILE` (
    `MIGRATION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `ORIGIN_AREA_ID` INT,
    `DESTINATION_AREA_ID` INT,
    `MIGRATION_REASON` VARCHAR(250),
    `SEX` VARCHAR(30),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_MIG` PRIMARY KEY (`MIGRATION_ID`),
    CONSTRAINT `UK_MIG` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `ORIGIN_AREA_ID`, `DESTINATION_AREA_ID`, `MIGRATION_REASON`, `SEX`),
    CONSTRAINT `FK_MIG_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_MIG_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`),
    CONSTRAINT `FK_MIG_3` FOREIGN KEY (`ORIGIN_AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_MIG_4` FOREIGN KEY (`DESTINATION_AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ETHNICITY_PROFILE` (
    `ETHNICITY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `ETHNIC_GROUP` VARCHAR(250),
    `SEX` VARCHAR(30),
    `INDICATOR_ID` INT,
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_ETH` PRIMARY KEY (`ETHNICITY_ID`),
    CONSTRAINT `UK_ETH` UNIQUE (`AREA_ID`, `YEAR`, `ETHNIC_GROUP`, `SEX`, `INDICATOR_ID`),
    CONSTRAINT `FK_ETH_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_ETH_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DIGITAL_ACCESS` (
    `DIGITAL_ACCESS_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `SEX` VARCHAR(30),
    `ACCESS_CATEGORY` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_DIG` PRIMARY KEY (`DIGITAL_ACCESS_ID`),
    CONSTRAINT `UK_DIG` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `SEX`, `ACCESS_CATEGORY`),
    CONSTRAINT `FK_DIG_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_DIG_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `HOUSING_CONDITION` (
    `HOUSING_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `DWELLING_TYPE` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_HOU` PRIMARY KEY (`HOUSING_ID`),
    CONSTRAINT `UK_HOU` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `DWELLING_TYPE`),
    CONSTRAINT `FK_HOU_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_HOU_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `BASIC_SERVICES_ACCESS` (
    `SERVICE_ACCESS_ID` INT NOT NULL,
    `AREA_ID` INT,
    `YEAR` SMALLINT,
    `INDICATOR_ID` INT,
    `SERVICE_CATEGORY` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_BSA` PRIMARY KEY (`SERVICE_ACCESS_ID`),
    CONSTRAINT `UK_BSA` UNIQUE (`AREA_ID`, `YEAR`, `INDICATOR_ID`, `SERVICE_CATEGORY`),
    CONSTRAINT `FK_BSA_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_BSA_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `HOUSEHOLD_EXPENDITURE` (
    `EXPENDITURE_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `EXPENDITURE_CATEGORY` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_HEX` PRIMARY KEY (`EXPENDITURE_ID`),
    CONSTRAINT `UK_HEX` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `EXPENDITURE_CATEGORY`),
    CONSTRAINT `FK_HEX_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_HEX_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CONSUMPTION_PATTERN` (
    `CONSUMPTION_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `CONSUMPTION_ITEM` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_CON` PRIMARY KEY (`CONSUMPTION_ID`),
    CONSTRAINT `UK_CON` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `CONSUMPTION_ITEM`),
    CONSTRAINT `FK_CON_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_CON_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `POVERTY_PROFILE` (
    `POVERTY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `POVERTY_LINE_TYPE` VARCHAR(250),
    `HOUSEHOLD_SIZE_GROUP` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_POV` PRIMARY KEY (`POVERTY_ID`),
    CONSTRAINT `UK_POV` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `POVERTY_LINE_TYPE`, `HOUSEHOLD_SIZE_GROUP`),
    CONSTRAINT `FK_POV_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_POV_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `INEQUALITY_PROFILE` (
    `INEQUALITY_ID` INT NOT NULL,
    `AREA_ID` INT,
    `SURVEY_YEAR` SMALLINT,
    `LOCALITY` VARCHAR(100),
    `INDICATOR_ID` INT,
    `POPULATION_GROUP` VARCHAR(250),
    `VALUE` DECIMAL(20,6),
    CONSTRAINT `PK_INEQ` PRIMARY KEY (`INEQUALITY_ID`),
    CONSTRAINT `UK_INEQ` UNIQUE (`AREA_ID`, `SURVEY_YEAR`, `LOCALITY`, `INDICATOR_ID`, `POPULATION_GROUP`),
    CONSTRAINT `FK_INEQ_1` FOREIGN KEY (`AREA_ID`) REFERENCES `ADMINISTRATIVE_AREA` (`AREA_ID`),
    CONSTRAINT `FK_INEQ_2` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATOR_DEFINITION` (`INDICATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
