SELECT 'AREA_LEVEL' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `AREA_LEVEL`
UNION ALL
SELECT 'ADMINISTRATIVE_AREA' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `ADMINISTRATIVE_AREA`
UNION ALL
SELECT 'MEASUREMENT_UNIT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `MEASUREMENT_UNIT`
UNION ALL
SELECT 'INDICATOR_DEFINITION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `INDICATOR_DEFINITION`
UNION ALL
SELECT 'POPULATION_CATEGORY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `POPULATION_CATEGORY`
UNION ALL
SELECT 'POPULATION_DEMOGRAPHY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `POPULATION_DEMOGRAPHY`
UNION ALL
SELECT 'DEMOGRAPHIC_RATIO' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `DEMOGRAPHIC_RATIO`
UNION ALL
SELECT 'HOUSEHOLD_STRUCTURE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `HOUSEHOLD_STRUCTURE`
UNION ALL
SELECT 'MARITAL_STATUS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `MARITAL_STATUS`
UNION ALL
SELECT 'RELIGION_DISTRIBUTION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `RELIGION_DISTRIBUTION`
UNION ALL
SELECT 'DISABILITY_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `DISABILITY_PROFILE`
UNION ALL
SELECT 'EDUCATION_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `EDUCATION_PROFILE`
UNION ALL
SELECT 'MIGRATION_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `MIGRATION_PROFILE`
UNION ALL
SELECT 'ETHNICITY_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `ETHNICITY_PROFILE`
UNION ALL
SELECT 'DIGITAL_ACCESS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `DIGITAL_ACCESS`
UNION ALL
SELECT 'HOUSING_CONDITION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `HOUSING_CONDITION`
UNION ALL
SELECT 'BASIC_SERVICES_ACCESS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `BASIC_SERVICES_ACCESS`
UNION ALL
SELECT 'HOUSEHOLD_EXPENDITURE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `HOUSEHOLD_EXPENDITURE`
UNION ALL
SELECT 'CONSUMPTION_PATTERN' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `CONSUMPTION_PATTERN`
UNION ALL
SELECT 'POVERTY_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `POVERTY_PROFILE`
UNION ALL
SELECT 'INEQUALITY_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM `INEQUALITY_PROFILE`;
